// The committed logo files, generated by scripts/clean_logo_svg.py from an
// export that always arrives with a white background baked in (the source
// editor can't produce a transparent SVG). Forgetting the cleaning step
// puts a white card on a near-black site, and nothing would report that
// but a person looking.

import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ASSETS = path.join(__dirname, "../assets");
const svgs = readdirSync(ASSETS).filter((f) => f.endsWith(".svg"));
const read = (f: string) => readFileSync(path.join(ASSETS, f), "utf8");

describe("every shipped logo SVG is actually clean", () => {
  it("finds the generated files", () => {
    expect(svgs).toContain("tranquilo-lockup-light.svg");
    expect(svgs).toContain("tranquilo-flower-violet.svg");
    expect(svgs).toContain("favicon.svg");
  });

  for (const f of svgs) {
    it(`${f} carries no background rectangle`, () => {
      expect(read(f)).not.toMatch(/<rect[^>]*fill="#ffffff"/i);
    });

    it(`${f} has a viewBox tightened to its artwork`, () => {
      // The export is a 1500x1500 canvas regardless of art size -- left
      // alone, the flower would render ~6px inside a 28px slot.
      const m = read(f).match(/viewBox="([^"]+)"/);
      expect(m, "no viewBox at all").toBeTruthy();
      const [, , w, h] = m![1].split(/\s+/).map(Number);
      expect(w, `${f} is still on the full canvas`).toBeLessThan(1000);
      expect(h, `${f} is still on the full canvas`).toBeLessThan(1000);
      expect(w).toBeGreaterThan(0);
      expect(h).toBeGreaterThan(0);
    });

    it(`${f} has no fixed width/height fighting CSS`, () => {
      expect(read(f)).not.toMatch(/<svg[^>]*\swidth="\d/);
    });
  }

  it("the favicon bakes its colour in rather than inheriting", () => {
    // A favicon has no CSS context; currentColor resolves to black, an
    // invisible icon on a browser's dark tab strip.
    expect(read("favicon.svg")).not.toContain("currentColor");
    expect(read("favicon.svg")).toContain("#8b5cf6");
  });

  it("keeps the supplied blue out of everything shipped", () => {
    // #004aad measures 2.41:1 against the site background, below the 3:1
    // floor for graphics.
    for (const f of svgs) {
      expect(
        read(f).toLowerCase(),
        `${f} still uses the original blue`,
      ).not.toContain("#004aad");
    }
  });

  it("preserves the sparkle's own cyan", () => {
    // Only the primary colour is swapped; the sparkle sits within a few
    // shades of the site's own accent teal.
    expect(read("tranquilo-lockup-light.svg").toLowerCase()).toContain(
      "#5ce1e6",
    );
  });
});

describe("the self-hosted typeface", () => {
  const FONTS = path.join(__dirname, "../assets/fonts");

  it("ships the woff2", () => {
    const f = readFileSync(
      path.join(FONTS, "GlacialIndifference-Regular.woff2"),
    );
    // wOF2 magic -- a .ttf renamed to .woff2 would load nowhere and the
    // wordmark would silently fall back to Work Sans.
    expect(f.subarray(0, 4).toString("latin1")).toBe("wOF2");
    expect(f.length).toBeLessThan(60_000);
  });

  it("ships the licence beside it, as the OFL requires", () => {
    const ofl = readFileSync(path.join(FONTS, "OFL.txt"), "utf8");
    expect(ofl).toContain("SIL OPEN FONT LICENSE");
    expect(ofl).toContain("Alfredo Marco Pradil");
  });

  it("the CSS points at the file that exists", () => {
    const cssPath = path.join(__dirname, "../css/style.css");
    const css = readFileSync(cssPath, "utf8");
    const m = css.match(/src:url\('([^']+\.woff2)'\)/);
    expect(m, "no @font-face src in the stylesheet").toBeTruthy();
    // Relative path, resolved from css/style.css's own location, since
    // that's how the browser resolves it too.
    const resolved = path.resolve(path.dirname(cssPath), m![1]);
    expect(
      existsSync(resolved),
      `${m![1]} does not resolve to a real file`,
    ).toBe(true);
    // swap, not block: a bar with a hole in it is worse than late letterforms.
    expect(css).toMatch(/font-display:\s*swap/);
  });

  it("keeps a fallback stack behind the brand face", () => {
    // --wordmark-font lives in css/tokens.css, not style.css.
    const css = readFileSync(path.join(__dirname, "../css/tokens.css"), "utf8");
    const m = css.match(/--wordmark-font:([^;]+);/);
    expect(m).toBeTruthy();
    expect(m![1]).toContain("Glacial Indifference");
    expect(m![1], "no fallback if the font fails to load").toContain(
      "Work Sans",
    );
  });
});

describe("the icon-only lockup", () => {
  it("has no wordmark paths left in it", () => {
    // The words are live text now -- leaving outlines in would ship the
    // wordmark twice and let the two drift apart.
    const svg = read("tranquilo-icon-light.svg");
    expect(svg).not.toContain("#2b43a3");
    expect(svg).not.toContain("translate(");
  });

  it("keeps the sparkle", () => {
    expect(read("tranquilo-icon-light.svg").toLowerCase()).toContain("#5ce1e6");
  });

  it("is materially smaller than the full lockup", () => {
    expect(read("tranquilo-icon-light.svg").length).toBeLessThan(
      read("tranquilo-lockup-light.svg").length * 0.6,
    );
  });
});
